### PR TITLE
Integrate lighthouse_coverage plugin

### PR DESCRIPTION
**Pull request by janbbeck**
This plugin emits a file for usage by the lighthouse coverage plugin for IDA pro and Binary Ninja. This is especially useful for the analysis of binaries that have advanced anti-debug and anti-tracing features and are heavily obfuscated with overlapping. Binary Ninja is capable of displaying overlapping code instructions.

### CODE REVIEW

**Comment by AndrewFasano** [comment]
Thanks for the PR! I started working on a similar plugin a while ago but never finished it.

Your comments about trying to get PANDA to build on Ubuntu 20.04 are a good point. Want to open an issue for that along with the errors you were seeing?

**Comment by AndrewFasano** [comment]
I doubt there's anything worth copying out of the plugin I had been working on, but if you're interested in comparing it's on a branch in 0717ff3d9bc8f6b336e4ed6d85dfc23492b59e59

**Comment by janbbeck** [comment]
> I doubt there's anything worth copying out of the plugin I had been working on, but if you're interested in comparing it's on a branch in [0717ff3](https://github.com/panda-re/panda/commit/0717ff3d9bc8f6b336e4ed6d85dfc23492b59e59)

Ha. Had I realized that, I would probably have worked on that instead :P

**Comment by janbbeck** [comment]
> Thanks for the PR! I started working on a similar plugin a while ago but never finished it.
> 
> Your comments about trying to get PANDA to build on Ubuntu 20.04 are a good point. Want to open an issue for that along with the errors you were seeing?

Yeah, going to get that going today.

**Pull request merged**
