### PR TITLE
Make PANDA startup quieter

### LINKED ISSUE #1329: PyPANDA startup is too verbose
This is too much output to print before anything my script does. I think we could get rid of all of it. Maybe we keep the panda args line, but even that's pretty useless.

```
using generic x86_64
os_name=[linux-64-ubuntu:4.15.0-72-generic-noaslr-nokaslr]
PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu:4.15.0-72-generic-noaslr-nokaslr
[PYPANDA] Panda args: [/home/andrew/git/panda/build/x86_64-softmmu/libpanda-x86_64.so -L /home/andrew/git/panda/build/pc-bios /home/andrew/.panda/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2 -display none -m 1024 -serial unix:/tmp/pypanda_sz_b10_8l,server,nowait -monitor unix:/tmp/pypanda_mw3fki_5o,server,nowait]
PPP automatically loaded plugin proc_start_linux
PANDA[core]:loading required plugin proc_start_linux
PANDA[core]:initializing proc_start_linux                                                                                                                                                                      
PANDA[core]:loading required plugin syscalls2                                                                                                                                                                  
PANDA[core]:initializing syscalls2                              
PANDA[syscalls2]:using profile for linux x64 64-bit
PANDA[core]:loading required plugin hw_proc_id                        
PANDA[core]:initializing hw_proc_id                                        
PANDA[core]:loading required plugin hooks                             
PANDA[core]:initializing hooks    
PANDA[core]:loading required plugin hw_proc_id                                                                                                                                                                 
PANDA[core]:/home/andrew/git/panda/build/x86_64-softmmu/panda/plugins/panda_hw_proc_id.so already loaded
PANDA[core]:loading required plugin osi                                             
PANDA[core]:initializing osi
PANDA[core]:loading required plugin osi_linux                                                   
PANDA[core]:initializing osi_linux
PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read                                                                                                                                                          
PANDA[core]:loading required plugin syscalls2          
PANDA[core]:/home/andrew/git/panda/build/x86_64-softmmu/panda/plugins/panda_syscalls2.so already loaded                                        
PANDA[core]:loading required plugin proc_start_linux
PANDA[core]:/home/andrew/git/panda/build/x86_64-softmmu/panda/plugins/panda_proc_start_linux.so already loaded
PANDA[core]:loading required plugin hooks                             
PANDA[core]:/home/andrew/git/panda/build/x86_64-softmmu/panda/plugins/panda_hooks.so already loaded
```

### PR DESCRIPTION
**Pull request by lacraig2**
This PR changes `callbacks.c` to use the `LOG_*` format (`LOG_ERROR`, `LOG_WARNING`, etc).

It also makes PANDA somewhat quieter by default with LOG formats that won't necessarily be seen for most items if PANDA's debug mode isn't set quite low.

### CODE REVIEW

**Review by AndrewFasano — APPROVED** [review]
So long as LOG_ERROR shows up by default (or maybe just always? Would be awkward to not print some of those errors) this looks great to me.

**Comment by lacraig2** [comment]
Yes. The default log level does show `LOG_ERROR`

**Comment by AndrewFasano** [comment]
@lacraig2 do you think we could silence more of these, either by reducing log level or changing what we log with pypanda?

I'm looking to silence this output from pypanda where I load syscalls2 and OSI

> PANDA[core]:os_familyno=2 bits=32 os_details=generic
> PANDA[syscalls2]:using profile for linux arm
> PANDA[osi_linux]:W> failed to read task.switch_task_hook_addr
> PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read

**Comment by lacraig2** [comment]
@AndrewFasano are you looking for a way to silence these generally or in a specific use case?

If you're willing to accept the latter we might consider building out an API around the `LOG_[LEVEL]_FILE` macros that let those be set dynamically and directed to a file. https://github.com/panda-re/panda/blob/1d0069ee8818fbfe0e3647e9b49d17e29644847e/panda/include/panda/debug.h#L73

**Comment by AndrewFasano** [comment]
I think I'd like to either
A) Modify this code so it's not logging for my specific use case, or
B) Make it more configurable

These logs aren't really important warnings so I'm not too opposed to option A - I think all 4 of these messages could be logged at the debug level

**Comment by lacraig2** [comment]
I think that 3 of 4 of those messages could be debug level.

The one that perhaps shouldn't be is:
> PANDA[osi_linux]:W> failed to read task.switch_task_hook_addr

I could see a case for the optional fields (like this one) being at the debug level.

I do think B makes sense in general.

**Pull request merged**
