### PR TITLE
Add IDAPython plugin to color tainted pseudocode lines

### PR DESCRIPTION
**Pull request by LauraLMann**
This IDAPython plugin works with the output of PANDA's ida_taint2 plugin.  It has only been tested with i386, but it seems useful as is.

### CODE REVIEW

**Comment by LauraLMann** [comment]
Travis ran out of time.  Close and reopen to get it to try again.

**Comment by LauraLMann** [comment]
Make Travis try again.

**Comment by LauraLMann** [comment]
In order to avoid the hassle of manually merging (and retesting) changes in 9 files I DID NOT TOUCH for this pull request, I am closing this pull request, and submitting another with the same work manually replayed (by me, not git) on the latest master.  At least, it's the latest now (the target keeps moving).  The replacement PR will be submitted as soon as Travis is happy on my fork.

**Comment by moyix** [comment]
Thanks and sorry for the hassle – I think the history rewrite to remove the large test files from the repo may have created some spurious conflicts...

**Comment by m000** [comment]
The regular rebase routine seemed to do the trick for this tree for this. Only additional step was a hard reset to discard the test file commits.

```
# fetch and checkout the PR branch
git fetch upstream pull/485/head:pr485
git checkout pr485

# identify the merge point with the current tree 
# prints 38f5795726d0 (merge of #487) which is a while back
git merge-base pr485 upstream/master

# rebase on the current tree
# this takes a while due to the large test file commits
git pull -r upstream master

# inspect - you can see the large test file commits at the top
git log

# drop the large test file commits
git reset --hard HEAD~2

# identify the new merge point
# prints 3717e524b19a (current head)
git merge-base pr485 upstream/master

# force push to update PR
git push -f origin
```

**Pull request closed without merging**
