### PR TITLE
Add flake.nix

### PR DESCRIPTION
**Pull request by be32826**
Add a Nix flake for PANDA.

After installing Nix with flakes support (e.g. with https://github.com/DeterminateSystems/nix-installer, the official installer doesn't enable flake support by default),

- `nix build` (in directory) or `nix build github:panda-re/panda` anywhere - Build and install PANDA into the Nix store and create a `result/` symlink to the installation.
- `nix shell` (in directory) or `nix shell github:panda-re/panda` anywhere - Enter a temporary development shell with the PANDA binaries in `PATH`.
- `nix develop` - Enter a development shell with all the build dependencies of PANDA (for debugging the build process)
- `nix flake update` - Update pinned dependencies in `flake.lock` lockfile.
- `nix bundle --bundler github:NixOS/bundlers#toDEB github:panda-re/panda` - Generate a .deb package for PANDA (currently puts a broken symlink in /usr/bin/panda, might need some tweaks)
- `nix bundle --bundler github:NixOS/bundlers#toRPM github:panda-re/panda` - Generate an RPM package
- `nix bundle --bundler github:NixOS/bundlers#toDockerImage` - Generate a minimal Docker image with PANDA

This doesn't have to replace the existing Docker container. It could just be an alternative install option like the install scripts in [panda/scripts](https://github.com/panda-re/panda/tree/dev/panda/scripts).

### CODE REVIEW

**Comment by AndrewFasano** [comment]
This looks interesting! Why does it delete the cargo locks, are those something we want to track in git? Might be of interest to @jamcleod

**Comment by be32826** [comment]
> This looks interesting! Why does it delete the cargo locks, are those something we want to track in git? Might be of interest to @jamcleod

It puts all the Rust plugins in a cargo workspace, so they share one lockfile instead of having their own separate ones. This makes it much easier to package in Nix, but it should also reduce build times/size because it makes the Rust plugins share a build artifact directory.

**Comment by be32826** [comment]
Also, I'm not sure why the RPATH length check exists or if removing it causes problems.

**Comment by MarkMankins** [comment]
My guess is that the rpath check is there to prevent one from going through an entire build only to have chrpath fail during the "make install" phase.  From the BUGS section in "man chrpath":

>       This  program  cannot create an RPATH tag if the ELF does not have one,
>       and it can only replace an RPATH with one of equal or  shorter  length.
>       (Moving  ELF sections following a lengthened string table would be dif‐
>       ficult and error-prone at best, and is  sometimes  outright  impossible
>       due to issues like limited ranges in jump instructions.)

**Comment by AndrewFasano** [comment]
The RPATH stuff was added in #533 to fix an issue with `make install` but we've talked about a better way to resolve plugin paths with $ORIGIN [here](https://github.com/panda-re/panda/issues/922#issuecomment-809442676). I never figured out how to get that working though.

Now that we've merged #1399 perhaps we could revisit that and come up with something better that would work for development environments, `make install` environments and our .deb package.

**Comment by MarkMankins** [comment]
Oh!  I didn't know about $ORIGIN.  Good write-up here about how that can be used:

https://www.baeldung.com/linux/rpath-change-in-binary  (Section 6)

**Comment by be32826** [comment]
I moved the Makefile patch into the `flake.nix` for now so it won't change the behavior of normal builds.

**Comment by jamcleod** [comment]
Thank you, sharing a lockfile/build directory has been something I've been interested in for the Rust plugins for a while.

**Comment by AndrewFasano** [comment]
Since this doesn't break the rust plugins, I don't see any reason not to merge (though I'll admit I still haven't figured out how to use flakes)

**Pull request merged**
