### PR TITLE
Port PANDA 1 'network' plugin to PANDA 2.

### PR DESCRIPTION
**Pull request by nathanjackson**
This PR brings in the PANDA 1 network plugin to PANDA 2. Tested with various protocols and operating systems.

Little changes were needed. I did have to add a call to `wtap_init(...)` and change the Makefile a little bit.

### CODE REVIEW

**Comment by nathanjackson** [comment]
Looks like there might be some issues with the version of the wireshark\wiretap libraries on Travis. There should be a workaround in place now.

**Comment by nathanjackson** [comment]
Another build timeout. Closing\reopening to retry.

**Comment by nathanjackson** [comment]
I added `travis_wait 35 sleep infinity &` which should prevent future build time outs.

**Comment by moyix** [comment]
Oof, sorry Travis is being so flaky. If you have any ideas on how to make it more reliable we would be very receptive to them.

**Comment by moyix** [comment]
Whew! Sorry that was such an ordeal :(

**Pull request merged**
