### PR TITLE
[Ready for review] Net transfer callbacks missing

### PR DESCRIPTION
**Pull request by scottcarr**
I'm going to attempt to port the callbacks from PANDA 1.0

See also #143

### CODE REVIEW

**Comment by scottcarr** [comment]
My current issue is this assert fails: https://github.com/scottcarr/panda/blob/master/panda/src/rr/rr_log.c#L263

According to my printf debugging size is 0.

This loop wasn't there in PANDA 1.0: https://github.com/scottcarr/panda/blob/master/hw/net/e1000.c#L1049-L1075

So, my porting in that area may be the problem.

**Comment by scottcarr** [comment]
I moved the calls to `rr_record_handle_packet_call` and `rr_record_net_transfer` in `e1000_receive_iov` into the do-while loop.  This may cause one `e1000_receive` call to generate multiple entries in the recording file, but that's kind of how the code works.  It doesn't crash during recording now.  Instead, my replay crashes in `rr_replay_skipped_calls_internal` because there is no `case RR_CALL_NET_TRANSFER` or `case RR_CALL_HANDLE_PACKET`.   That's to be expected.  I'll need to implement those cases.

**Comment by scottcarr** [comment]
I implemented `panda_callbacks_handle_packet` and panda_callbacks_net_transfer` and invoke them inside of `rr_replay_skipped_calls_internal`.  I think the replay/record piece may be complete.  I'll attempt to create a test plugin.

**Comment by scottcarr** [comment]
I think this is working reasonably well.  My plugin prints plausible looking data.  Can someone with write access take a look please?  Maybe @moyix?  Thanks.

**Comment by scottcarr** [comment]
ping @tleek @moyix Any thoughts on this PR?  Thanks.

**Comment by moyix** [comment]
I think this looks good, thanks for putting it together! :)

**Pull request merged**
