### PR TITLE
WIP: Llvm trace2

### PR DESCRIPTION
**Pull request by wangray**
TODO: 
* Be able to vectorize pandalog entries in C++, so entire trace can be aligned
* Add statistics to slice_analyzer
* Lower LLVM back to guest assembly
* Add coverage tools for IDA pro

### CODE REVIEW

**Comment by Manouchehri** [comment]
Looks like a few things got broken by e232ca4102846b7a6e530ce49126a55cf194342d. I can build from 50bddc73270857a435b497d609a63bd091945a63 without a problem.

```
...
  CXX     ppc-softmmu/panda/plugins/win7x86intro/win7x86intro.o
  CC      ppc-softmmu/panda/plugins/scissors/scissors.o
  CXX     ppc-softmmu/panda/plugins/pri_taint/pri_taint.o
  CXX     ppc-softmmu/panda/plugins/pri_trace/pri_trace.o
  CXX     ppc-softmmu/panda/plugins/tainted_branch/tainted_branch.o
  CXX     ppc-softmmu/panda/plugins/taint2/llvm_taint_lib.o
  CC      x86_64-softmmu/target/i386/translate.o
  CC      i386-softmmu/target/i386/translate.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/syscalls2.o
  CXX     ppc-softmmu/panda/plugins/tstringsearch/tstringsearch.o
  GEN     arm-softmmu/config-target.h
  GEN     trace/generated-helpers.c
  PLUGIN  ppc-softmmu/panda/plugins/panda_wintrospection.so
  PLUGIN  ppc-softmmu/panda/plugins/panda_memsavep.so
  PLUGIN  ppc-softmmu/panda/plugins/panda_replaymovie.so
  GEN     trace/generated-helpers.c
  CC      arm-softmmu/panda/plugins/scissors/scissors.o
  PLUGIN  ppc-softmmu/panda/plugins/panda_win7x86intro.so
  CXX     i386-softmmu/panda/plugins/callstack_instr/callstack_instr.o
  CC      i386-softmmu/panda/plugins/checkpoint_test/checkpoint_test.o
  CXX     i386-softmmu/panda/plugins/libfi/libfi.o
  PLUGIN  ppc-softmmu/panda/plugins/panda_scissors.so
  CXX     ppc-softmmu/panda/plugins/taint2/taint2.o
  CXX     ppc-softmmu/panda/plugins/taint2/taint_api.o
/panda/target/i386/translate.c: In function 'gen_intermediate_code':
/panda/target/i386/translate.c:8568:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for(int pc_i = pc_start, i = 0; pc_i < pc_ptr; pc_i++, i++){
     ^
/panda/target/i386/translate.c:8568:5: note: use option -std=c99 or -std=gnu99 to compile your code
/panda/target/i386/translate.c: In function 'gen_intermediate_code':
/panda/target/i386/translate.c:8568:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for(int pc_i = pc_start, i = 0; pc_i < pc_ptr; pc_i++, i++){
     ^
/panda/target/i386/translate.c:8568:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [target/i386/translate.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  CLANGXX ppc-softmmu/panda/plugins/taint2/taint_ops_llvm.bc
  PLUGIN  i386-softmmu/panda/plugins/panda_checkpoint_test.so
make[1]: *** [target/i386/translate.o] Error 1
make: *** [subdir-x86_64-softmmu] Error 2
make: *** Waiting for unfinished jobs....
  CXX     arm-softmmu/panda/plugins/syscalls2/syscalls2.o
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_linux_arm.o
  PLUGIN  ppc-softmmu/panda/plugins/panda_tstringsearch.so
  PLUGIN  arm-softmmu/panda/plugins/panda_scissors.so
  PLUGIN  ppc-softmmu/panda/plugins/panda_pri_trace.so
  CXX     ppc-softmmu/panda/plugins/tainted_instr/tainted_instr.o
  CXX     arm-softmmu/panda/plugins/win7x86intro/win7x86intro.o
  PLUGIN  ppc-softmmu/panda/plugins/panda_file_taint.so
  CXX     ppc-softmmu/panda/plugins/llvm_trace2/llvm_trace2.o
  PLUGIN  ppc-softmmu/panda/plugins/panda_pri_taint.so
  CLANG   ppc-softmmu/fpu/softfloat.bc2
  CLANG   ppc-softmmu/target/ppc/excp_helper.bc2
  PLUGIN  ppc-softmmu/panda/plugins/panda_asid_instr_count.so
  PLUGIN  arm-softmmu/panda/plugins/panda_win7x86intro.so
  CLANG   ppc-softmmu/target/ppc/fpu_helper.bc2
  PLUGIN  ppc-softmmu/panda/plugins/panda_tainted_branch.so
  CC      arm-softmmu/panda/plugins/wintrospection/wintrospection.o
  CLANG   ppc-softmmu/target/ppc/timebase_helper.bc2
  CLANG   ppc-softmmu/target/ppc/misc_helper.bc2
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_linux_arm.o
  CLANG   ppc-softmmu/target/ppc/mmu_helper.bc2
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_linux_arm.o
  PLUGIN  arm-softmmu/panda/plugins/panda_wintrospection.so
  CLANG   ppc-softmmu/target/ppc/mem_helper.bc2
  PLUGIN  i386-softmmu/panda/plugins/panda_libfi.so
  CLANG   ppc-softmmu/target/ppc/int_helper.bc2
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_linux_arm.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_linux_x86.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_linux_x86.o
  LLVMLD  ppc-softmmu/panda/plugins/panda_taint2_ops.bc
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_linux_x86.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_windowsxp_sp2_x86.o
  CC      ppc-softmmu/panda/src/callbacks.o
  PLUGIN  ppc-softmmu/panda/plugins/panda_tainted_instr.so
  CC      ppc-softmmu/panda/src/callback_support.o
  CC      ppc-softmmu/panda/src/common.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_windowsxp_sp2_x86.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_windowsxp_sp3_x86.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_windowsxp_sp3_x86.o
  PLUGIN  i386-softmmu/panda/plugins/panda_callstack_instr.so
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_linux_x86.o
make: *** [subdir-i386-softmmu] Error 2
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_windowsxp_sp2_x86.o
  CC      ppc-softmmu/panda/src/plog.o
  CXX     ppc-softmmu/panda/src/plog-cc.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_windows7_x86.o
  CXX     ppc-softmmu/panda/llvm/tcg-llvm.o
  CXX     ppc-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_windows7_x86.o
  CXX     arm-softmmu/panda/plugins/asid_instr_count/asid_instr_count.o
  CXX     ppc-softmmu/panda/llvm/helper_runtime.o
  CC      ppc-softmmu/exec.o
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_windowsxp_sp2_x86.o
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_windowsxp_sp3_x86.o
  CC      arm-softmmu/panda/plugins/replaymovie/replaymovie.o
  CC      arm-softmmu/panda/plugins/memsavep/memsavep.o
  PLUGIN  ppc-softmmu/panda/plugins/panda_syscalls2.so
In file included from /usr/include/dlfcn.h:24:0,
                 from /panda/panda/include/panda/plugin_plugin.h:5,
                 from /panda/panda/include/panda/plugin.h:738,
                 from /panda/panda/plugins/llvm_trace2/llvm_trace2.h:20,
                 from /panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:25:
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp: In function 'void llvm::llvm_init()':
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:288:33: error: expected type-specifier before 'CPUX86State'
   printf("eip: %lu\n", offsetof(CPUX86State, eip)/4);
                                 ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:288:33: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:288:24: error: expected ')' before ',' token
   printf("eip: %lu\n", offsetof(CPUX86State, eip)/4);
                        ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:289:36: error: expected type-specifier before 'CPUX86State'
   printf("cc_dst: %lu\n", offsetof(CPUX86State, cc_dst)/4);
                                    ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:289:36: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:289:27: error: expected ')' before ',' token
   printf("cc_dst: %lu\n", offsetof(CPUX86State, cc_dst)/4);
                           ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:290:38: error: expected type-specifier before 'CPUX86State'
   printf("xmm_regs: %lu\n", offsetof(CPUX86State, xmm_regs)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:290:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:290:29: error: expected ')' before ',' token
   printf("xmm_regs: %lu\n", offsetof(CPUX86State, xmm_regs)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:291:34: error: expected type-specifier before 'CPUX86State'
   printf("segs: %lu\n", offsetof(CPUX86State, segs)/4);
                                  ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:291:34: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:291:25: error: expected ')' before ',' token
   printf("segs: %lu\n", offsetof(CPUX86State, segs)/4);
                         ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:292:34: error: expected type-specifier before 'CPUX86State'
   printf("ldt : %lu\n", offsetof(CPUX86State, ldt)/4);
                                  ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:292:34: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:292:25: error: expected ')' before ',' token
   printf("ldt : %lu\n", offsetof(CPUX86State, ldt)/4);
                         ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:293:33: error: expected type-specifier before 'CPUX86State'
   printf("tr : %lu\n", offsetof(CPUX86State, tr)/4);
                                 ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:293:33: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:293:24: error: expected ')' before ',' token
   printf("tr : %lu\n", offsetof(CPUX86State, tr)/4);
                        ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:294:38: error: expected type-specifier before 'CPUX86State'
   printf("segs gdt: %lu\n", offsetof(CPUX86State, gdt)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:294:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:294:29: error: expected ')' before ',' token
   printf("segs gdt: %lu\n", offsetof(CPUX86State, gdt)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:295:38: error: expected type-specifier before 'CPUX86State'
   printf("segs idt: %lu\n", offsetof(CPUX86State, idt)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:295:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:295:29: error: expected ')' before ',' token
   printf("segs idt: %lu\n", offsetof(CPUX86State, idt)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:296:38: error: expected type-specifier before 'CPUX86State'
   printf("cr array: %lu\n", offsetof(CPUX86State, cr)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:296:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:296:29: error: expected ')' before ',' token
   printf("cr array: %lu\n", offsetof(CPUX86State, cr)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:297:38: error: expected type-specifier before 'CPUX86State'
   printf("bnd_regs: %lu\n", offsetof(CPUX86State, bnd_regs)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:297:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:297:29: error: expected ')' before ',' token
   printf("bnd_regs: %lu\n", offsetof(CPUX86State, bnd_regs)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:298:36: error: expected type-specifier before 'CPUX86State'
   printf("fpregs: %lu\n", offsetof(CPUX86State, fpregs)/4);
                                    ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:298:36: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:298:27: error: expected ')' before ',' token
   printf("fpregs: %lu\n", offsetof(CPUX86State, fpregs)/4);
                           ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:299:34: error: expected type-specifier before 'CPUX86State'
   printf("fpop: %lu\n", offsetof(CPUX86State, fpop)/4);
                                  ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:299:34: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:299:25: error: expected ')' before ',' token
   printf("fpop: %lu\n", offsetof(CPUX86State, fpop)/4);
                         ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:302:48: error: expected type-specifier before 'CPUX86State'
   printf("exception_next_eip: %lu\n", offsetof(CPUX86State, exception_next_eip)/4);
                                                ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:302:48: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:302:39: error: expected ')' before ',' token
   printf("exception_next_eip: %lu\n", offsetof(CPUX86State, exception_next_eip)/4);
                                       ^
  CXX     arm-softmmu/panda/plugins/file_taint/file_taint.o
  CC      ppc-softmmu/translate-all.o
  PLUGIN  arm-softmmu/panda/plugins/panda_replaymovie.so
  CC      ppc-softmmu/cpu-exec.o
  LLVMLD  ppc-softmmu/llvm-helpers.bc1
  CXX     arm-softmmu/panda/plugins/pri_taint/pri_taint.o
  PLUGIN  arm-softmmu/panda/plugins/panda_memsavep.so
  CXX     arm-softmmu/panda/plugins/pri_trace/pri_trace.o
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_windowsxp_sp3_x86.o
make[2]: *** [panda/plugins/llvm_trace2/llvm_trace2.o] Error 1
make[1]: *** [plugin-llvm_trace2] Error 2
make[1]: *** Waiting for unfinished jobs....
  CXX     arm-softmmu/panda/plugins/taint2/llvm_taint_lib.o
  PLUGIN  arm-softmmu/panda/plugins/panda_asid_instr_count.so
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_enter_windows7_x86.o
  CXX     arm-softmmu/panda/plugins/tainted_branch/tainted_branch.o
  CXX     arm-softmmu/panda/plugins/tstringsearch/tstringsearch.o
  CXX     arm-softmmu/panda/plugins/tainted_instr/tainted_instr.o
  PLUGIN  arm-softmmu/panda/plugins/panda_file_taint.so
  CXX     arm-softmmu/panda/plugins/llvm_trace2/llvm_trace2.o
  CXX     arm-softmmu/panda/plugins/syscalls2/gen_syscall_switch_return_windows7_x86.o
  PLUGIN  arm-softmmu/panda/plugins/panda_pri_taint.so
  PLUGIN  arm-softmmu/panda/plugins/panda_pri_trace.so
  CLANG   arm-softmmu/fpu/softfloat.bc2
  CXX     arm-softmmu/panda/plugins/taint2/taint2.o
  CLANG   arm-softmmu/target/arm/op_helper.bc2
  CLANG   arm-softmmu/target/arm/helper.bc2
  PLUGIN  arm-softmmu/panda/plugins/panda_tstringsearch.so
  CLANG   arm-softmmu/target/arm/neon_helper.bc2
  CLANG   arm-softmmu/target/arm/iwmmxt_helper.bc2
  PLUGIN  arm-softmmu/panda/plugins/panda_tainted_instr.so
  PLUGIN  ppc-softmmu/panda/plugins/panda_taint2.so
  CLANG   arm-softmmu/target/arm/crypto_helper.bc2
  CC      arm-softmmu/panda/src/callbacks.o
  PLUGIN  arm-softmmu/panda/plugins/panda_tainted_branch.so
  CC      arm-softmmu/panda/src/callback_support.o
  CC      arm-softmmu/panda/src/common.o
  CC      arm-softmmu/panda/src/plog.o
  CC      arm-softmmu/exec.o
  CC      arm-softmmu/translate-all.o
  CC      arm-softmmu/cpu-exec.o
  CXX     arm-softmmu/panda/plugins/taint2/taint_api.o
  CLANGXX arm-softmmu/panda/plugins/taint2/taint_ops_llvm.bc
  LLVMLD  arm-softmmu/llvm-helpers.bc1
  LLMORPH arm-softmmu/llvm-helpers.bc
In file included from /usr/include/dlfcn.h:24:0,
                 from /panda/panda/include/panda/plugin_plugin.h:5,
                 from /panda/panda/include/panda/plugin.h:738,
                 from /panda/panda/plugins/llvm_trace2/llvm_trace2.h:20,
                 from /panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:25:
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp: In function 'void llvm::llvm_init()':
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:288:33: error: expected type-specifier before 'CPUX86State'
   printf("eip: %lu\n", offsetof(CPUX86State, eip)/4);
                                 ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:288:33: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:288:24: error: expected ')' before ',' token
   printf("eip: %lu\n", offsetof(CPUX86State, eip)/4);
                        ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:289:36: error: expected type-specifier before 'CPUX86State'
   printf("cc_dst: %lu\n", offsetof(CPUX86State, cc_dst)/4);
                                    ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:289:36: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:289:27: error: expected ')' before ',' token
   printf("cc_dst: %lu\n", offsetof(CPUX86State, cc_dst)/4);
                           ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:290:38: error: expected type-specifier before 'CPUX86State'
   printf("xmm_regs: %lu\n", offsetof(CPUX86State, xmm_regs)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:290:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:290:29: error: expected ')' before ',' token
   printf("xmm_regs: %lu\n", offsetof(CPUX86State, xmm_regs)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:291:34: error: expected type-specifier before 'CPUX86State'
   printf("segs: %lu\n", offsetof(CPUX86State, segs)/4);
                                  ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:291:34: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:291:25: error: expected ')' before ',' token
   printf("segs: %lu\n", offsetof(CPUX86State, segs)/4);
                         ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:292:34: error: expected type-specifier before 'CPUX86State'
   printf("ldt : %lu\n", offsetof(CPUX86State, ldt)/4);
                                  ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:292:34: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:292:25: error: expected ')' before ',' token
   printf("ldt : %lu\n", offsetof(CPUX86State, ldt)/4);
                         ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:293:33: error: expected type-specifier before 'CPUX86State'
   printf("tr : %lu\n", offsetof(CPUX86State, tr)/4);
                                 ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:293:33: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:293:24: error: expected ')' before ',' token
   printf("tr : %lu\n", offsetof(CPUX86State, tr)/4);
                        ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:294:38: error: expected type-specifier before 'CPUX86State'
   printf("segs gdt: %lu\n", offsetof(CPUX86State, gdt)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:294:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:294:29: error: expected ')' before ',' token
   printf("segs gdt: %lu\n", offsetof(CPUX86State, gdt)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:295:38: error: expected type-specifier before 'CPUX86State'
   printf("segs idt: %lu\n", offsetof(CPUX86State, idt)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:295:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:295:29: error: expected ')' before ',' token
   printf("segs idt: %lu\n", offsetof(CPUX86State, idt)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:296:38: error: expected type-specifier before 'CPUX86State'
   printf("cr array: %lu\n", offsetof(CPUX86State, cr)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:296:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:296:29: error: expected ')' before ',' token
   printf("cr array: %lu\n", offsetof(CPUX86State, cr)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:297:38: error: expected type-specifier before 'CPUX86State'
   printf("bnd_regs: %lu\n", offsetof(CPUX86State, bnd_regs)/4);
                                      ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:297:38: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:297:29: error: expected ')' before ',' token
   printf("bnd_regs: %lu\n", offsetof(CPUX86State, bnd_regs)/4);
                             ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:298:36: error: expected type-specifier before 'CPUX86State'
   printf("fpregs: %lu\n", offsetof(CPUX86State, fpregs)/4);
                                    ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:298:36: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:298:27: error: expected ')' before ',' token
   printf("fpregs: %lu\n", offsetof(CPUX86State, fpregs)/4);
                           ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:299:34: error: expected type-specifier before 'CPUX86State'
   printf("fpop: %lu\n", offsetof(CPUX86State, fpop)/4);
                                  ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:299:34: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:299:25: error: expected ')' before ',' token
   printf("fpop: %lu\n", offsetof(CPUX86State, fpop)/4);
                         ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:302:48: error: expected type-specifier before 'CPUX86State'
   printf("exception_next_eip: %lu\n", offsetof(CPUX86State, exception_next_eip)/4);
                                                ^
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:302:48: error: expected ',' before 'CPUX86State'
/panda/panda/plugins/llvm_trace2/llvm_trace2.cpp:302:39: error: expected ')' before ',' token
   printf("exception_next_eip: %lu\n", offsetof(CPUX86State, exception_next_eip)/4);
                                       ^
make[2]: *** [panda/plugins/llvm_trace2/llvm_trace2.o] Error 1
make[1]: *** [plugin-llvm_trace2] Error 2
make[1]: *** Waiting for unfinished jobs....
  LLVMLD  arm-softmmu/panda/plugins/panda_taint2_ops.bc
  PLUGIN  arm-softmmu/panda/plugins/panda_taint2.so
make: *** [subdir-ppc-softmmu] Error 2
  PLUGIN  arm-softmmu/panda/plugins/panda_syscalls2.so
make: *** [subdir-arm-softmmu] Error 2
```

**Comment by wangray** [comment]
Oh god this is not nearly ready to use yet, I'll let you know when it's done.

**Comment by Manouchehri** [comment]
Haha don't worry, I'm just poking around for fun. =)

**Comment by Manouchehri** [comment]
@wangray Should I give it a go, or still stay away? 😄

**Comment by wangray** [comment]
I haven't tested on anything except simple x86 Linux programs so far, and am also continually changing the interface, so might not be a good idea. I would like to make sure it works with larger, more complex/realistic programs as well. 

You can see a usage guide, which I will continue to update, here: https://hackmd.io/c/SknwI0uLz/%2FBwTmFMCMBZoYwLQFY4HYQOqyqGRAGa7CoHRIAMAjCKtJEkA%3D

**Pull request closed without merging**
