### PR TITLE
new syscalls2 callbacks with richer interface + misc

### PR DESCRIPTION
**Pull request by m000**
Added two new callbacks `on_all_sys_enter2` and `on_all_sys_return2`. The new callbacks provide other plugins with rich information about executing system calls and their context. This eliminates the need to re-implement this functionality in plugins that use `syscalls2`. This was a gap left by the thin versions of the callbacks (`on_all_sys_enter` and `on_all_sys_return`).

On the side, some generic logging macros were added to `panda/debug.h`. Finally, `panda/types.h` was added for defining custom types to be reused across PANDA. Currently, `target_ptr_t` and `target_pid_t` are defined. These are merely aliases for the ubiquitous `target_ulong`, meant to make plugin code more readable.

### CODE REVIEW

**Comment by moyix** [comment]
Is this ready for review/merge?

**Comment by m000** [comment]
Should be good now.

**Comment by moyix** [comment]
It looks like that last commit broke something, could you have a look?

https://travis-ci.org/panda-re/panda/builds/448365785#L2932-L2947

**Comment by moyix** [comment]
Thanks!

**Pull request merged**
