### PR TITLE
Fix proc_start_linux issues #973 It is based on refcount.

### PR DESCRIPTION
**Pull request by fengjian**
Fix proc_start_linux_issues #973

### CODE REVIEW

**Comment by AndrewFasano** [comment]
@lacraig2 can you review this? I'm not familiar with proc_start_linux

**Review by lacraig2 — CHANGES_REQUESTED** [review]
Sorry about the delay. It's been busy.

The refcount code is valid and worth adding.

The procfilter is neat, but I would like to see the plugin not have an additional dependency on osi. It would be acceptable to have a mode of this plugin that does this filtering, but not an absolute dependency.

**Comment by AndrewFasano** [comment]
Any chance we could split out the refcount code to get it merged and then hold off on merging the procfilter stuff until the requested changes are made?

**Comment by AndrewFasano** [comment]
Sorry, the current settings for the stale issue/PR bot are a little aggressive, I think it would be great to this (or maybe just some of this?) merged.

**Comment by fengjian** [comment]
> Any chance we could split out the refcount code to get it merged and then hold off on merging the procfilter stuff until the requested changes are made?

This has the possibility.

**Pull request closed without merging**
