### PR TITLE
use current x86 processor mode when disassemble in i386

### PR DESCRIPTION
**Pull request by LauraLMann**
Always using 32-bit mode in capstone causes problems when disassembling x86 16-bit binaries (running in 32-bit OS, such as FreeDOS), as some instructions are misinterpreted, causing call statements to be missed occasionally as their bytes (or some of them) are absorbed into the previous, erroneously disassembled, instruction.  Changing the mode in capstone as the processor mode in PANDA changes deals with this issue.

### CODE REVIEW

**Comment by moyix** [comment]
Thanks for the contribution! We currently check whether the processor is running in 64 or 32 bit mode, but we missed the case where it may be running in 16-bit mode.

Do you think you could move your changes here:

https://github.com/LauraLMann/panda/blob/eb1b5b680fdd4757ac1946cefb72ac260786d9c6/panda/plugins/callstack_instr/callstack_instr.cpp#L181-L184

So that they're all in a single location? That's also where we decide on ARM vs Thumb mode.

**Comment by LauraLMann** [comment]
The disas_block function doesn't have access to the TranslationBlock (passed in to after_block_translate) that is needed to determine what the current mode is.
What is your preferred way to deal with this?  Change the signature of disas_block to pass in the new modeBit (and ignore it unless in the 32-bit i386 build), or turn modeBit into a file-level variable (like cs_handle_32), or something else?  Or is it 'programmer's choice'?

**Comment by moyix** [comment]
I believe that the same information is also accessible by checking `env->hflags & HF_CS32_MASK`, which is already passed into `disas_block`.

**Comment by LauraLMann** [comment]
Closing to force a rebuild in Travis.

**Comment by LauraLMann** [comment]
Closing and reopening to force a rebuild - hopefully Travis is working now.

**Comment by moyix** [comment]
Looks great, thank you!

**Pull request merged**
