### PR TITLE
improvements in filename resolution for osi_linux

### PR DESCRIPTION
**Pull request by m000**
**The good:** Mounted filename resolution now *mostly* works for recent kernels. Moreover, we have partial resolution of dynamic filenames.

**The bad:** Mounts deeper than 1st level may still not work. Needs testing. Also needs testing with older kernels.

**The ugly:** This required the extraction of additional offset. Most of the configurations in `kernelinfo.conf` are now obsolete. Time for a cleanup?

### CODE REVIEW

**Comment by moyix** [comment]
Nice. As for the kernelinfo question - maybe we can simply generate these
from the Volatility Linux profiles? They have a lot of kernels and
distributions covered and should contain all of the data structures and
offsets (and, I believe, global variables) for the kernel.

https://github.com/volatilityfoundation/profiles

**Comment by m000** [comment]
Ok. Will check to see if we can reuse volatility's data.

Please hold merging until tomorrow. I want to make another pass on the code and see if I've missed any glitches.

**Comment by moyix** [comment]
Cool. Just to check, this still works with the older kernels as well? (In particular we should try not to break the kernel version that the `run_debian.py` script uses)

**Comment by m000** [comment]
It should be running after having the offsets regenerated.
I can see that the url for the used VM is in the script, so I'll download
it, make sure it runs, and get back to you.

M.

**Comment by moyix** [comment]
Cool. If you want a pretty easy test, you should be able to just do

`../panda/scripts/run_debian.py ls`

And then replay with `asidstory` to make sure OSI is working.

**Comment by m000** [comment]
Updated kernelinfo.conf to work with wheezy_panda2.qcow2, tested with a custom recording. So this should be ready to merge.

Couldn't find where run_debian.py script specifies the kernel profile to use. The script may need updating.

**Comment by m000** [comment]
I removed the `lava32:32` section to keep kernelinfo.conf uncluttered—it was identical to `debian:3.2.0-4-686-pae:32`. I have added a comment to show this.

https://github.com/panda-re/panda/blob/6cda540512f7d175e2ed56a7e8925b2ca89d753f/panda/plugins/osi_linux/kernelinfo.conf#L55-L58

**Comment by m000** [comment]
Yes, that's right.
If you have to changes multiple lava scripts, maybe it's easier to comment
the verbose section label and uncomment the lava section label.

M.

**Pull request merged**
