### PR TITLE
tapindex: improvements and some script work.

### PR DESCRIPTION
**Pull request by hanetzer**
Seems to work fine and record threaded stack types. idx.py is modified to work on
py3, but still only appears to work with asid style records. I don't understand enough
python and numpy to make it work with threaded records, hoping for some help here.

Also working on memdump, seems to work (will be another PR)

### CODE REVIEW

**Comment by hanetzer** [comment]
Wait what. How in tf did you make a commit on my repo?

**Comment by hanetzer** [comment]
@AndrewFasano Don't know how you did it, but I'd appreciate you not pushing commits
into my fork. If ya'll want a bunch of merge commits here, fine, but I don't enjoy the clutter.

**Comment by AndrewFasano** [comment]
Hey, sorry. I thought this was ready to merge so I clicked the button on this page that merges master into your branch. Then once CI passed I was going to rebase it onto master to avoid the merge commit. That’s how I’ve been getting CI to run on PRs to ensure the code passes our tests when run on the latest code. Is that bad git practice? Is there a better way when a PR falls behind master?

**Comment by hanetzer** [comment]
My general procedure is to not use any of github's merge/etc stuff. Like, were this my repo, and I wanted to merge this pr, I'd add the fork as a remote, pull it in, rebase it on master and merge it.
Merge commits are sometimes a needed evil on large scope projects (like merging the latest gpu
drivers from the drm repo into linux upstream) but for small stuff like this its generally uneeded.

If I, as a contributor to a repo, notice that its falling behind master I will typically do the rebase and
repush every now and then if it takes a while for the change to be accepted.

On another note, I've noticed that the pr that ported to this plugin didn't actually add it to the config
file for plugins, so its not being built?

**Comment by hanetzer** [comment]
Basically the 'better way' is for contributors to keep current imo. No code-dumps, so to speak.

**Pull request closed without merging**
