### PR TITLE
Update Arch install script to include new GPG keys.

### PR DESCRIPTION
**Pull request by ajgay**
Tested on Manjaro 18.1.1.

### CODE REVIEW

**Comment by moyix** [comment]
Thanks for this! Will merge now.

**Comment by nathanjackson** [comment]
Whoa, is this supposed to have the PANDA binaries in it now under `install/`?

**Comment by nathanjackson** [comment]
This probably needs to be backed out... we really don't want binaries in the repo.

**Comment by ajgay** [comment]
I don't believe my initial commit was responsible for that. If you look at the diff for 654c025 you see its very simple. I did notice that `build.sh` did default to the local `install` directory however. That seems to be fixed with the latest merge however, no?

**Comment by ajgay** [comment]
Sorry, just noticed you meant pre-build binaries in `install` not the target of the `build.sh` script. Agreed the bins should be removed. Not sure how they slipped through.

**Comment by nathanjackson** [comment]
This commit added the binaries to the repository: 3acf5d4c67e7e7ad2e77b0df9fd2fc71a2313ac4. Since this is a merge from upstream into your fork, it probably means your master branch was out of date from a few weeks back when someone else I think pushed binaries into the repo.

@moyix You probably want to fix this before accepting any additional PRs by removing the relevant commits from the history and force pushing, otherwise the binaries will always exist in the repo.

If you need help, I more or less know what needs to be done.

**Comment by m000** [comment]
The PR needed rebasing before merging. I can see several commits from previous PRs that have already been merged.
@ajgay use `git pull -r upstream master` to rebase your PRs onto master, rather than merging with master. This generally produces cleaner PRs.

**Comment by m000** [comment]
@moyix I think that the quickest solution would be: (a) doing a hard reset to the HEAD before this was merged, (b) cherry-picking 654c025, (c) force-pushing.

@ajgay 654c025 is the only thing you wanted to include, right?

**Comment by ajgay** [comment]
@m000 Yes, that is the only needed commit. The rest were added as a simple merge as the PR sat for several weeks.

**Pull request merged**
