### PR TITLE
Enhanced Callstack Segregation Options

### PR DESCRIPTION
**Pull request by LauraLMann**
The main thing was to add an option to use the process ID and thread ID to segregate callstacks.  This does a better job of distinguishing between stacks than the ASID.  This technique does require OSI support, so the ASID and USE_STACK_HEURISTIC techniques are still available in case OSI is not available for one's guest OS.  Note that if an OS is specified (via the -os switch), that this new technique (called "threaded") is used instead of ASID.  The "asid" technique remains the default if no OS is specified.
Also changed the old USE_STACK_HEURISTIC option, which was formerly made available only at build time, to now be a run-time option.
Also adjusted the get_prog_point API in callstack_instr, and the plugins which rely upon it (stringsearch, textprinter, unigrams) to not assume the callstacks were segregated via ASID.
I think this takes care of issue #411.

### CODE REVIEW

**Comment by LauraLMann** [comment]
Please put a pause on this pull request until I figure out where an infrequent seg fault is coming from.  I don't KNOW it's from these changes, but it did appear shortly after they were made...

**Comment by LauraLMann** [comment]
OK, I've got the seg fault fixed (yes, it was my problem - mea culpa).  Close and reopen to force Travis to review the changes.

**Comment by LauraLMann** [comment]
Reopening to force Travis to start up again.

**Comment by LauraLMann** [comment]
My changes are done now, and Travis is happy.  Please review to see if these enhancements to the callstack_instr plugin (resolving issue #411) are acceptable.

**Comment by moyix** [comment]
This is great! Thanks in particular for taking the time to update the various plugins that use tap points. Very much appreciated :)

**Pull request merged**
