### PR TITLE
[FORKED]PANDA

### PR DESCRIPTION
**Pull request by vlaze**
[WIP]

### CODE REVIEW

**Comment by vlaze** [comment]
...that's what happens when you have never pull requested before.

**Comment by moyix** [comment]
Thanks for the pull request! I'll try to have a look at this and get it merged soon.

**Comment by vlaze** [comment]
That's OK! I'll be waiting for more news. Sorry for the mess and the million commits, it's the first time I'm doing this.

**Comment by m000** [comment]
Hi @vlaze. Some quick comments:

- A pull request that changes the licence of the project? That's kind of rude... :)
- Can you squash commits and edit the messages to explain why you introduce each change? E.g. message "Add files via upload" doesn't make any sense to the rest of us.
- Why is `config-devices.mak` needed? Inside it mentions "Default configuration for x86_64-softmmu". But it appears to me that it will be used for all architectures (?) -- i.e. there's no logic to activate it only for x86_64.
- Why is `archer.sh` script needed? It is surprising that nobody needed copying these files before. Also, if you *really* need the files there, it is better to softlink them (so you don't have two copies that can become out of sync).

**Comment by vlaze** [comment]
Hello @m000, thank you for answering. I'll implement those changes as soon as I can. I had some problems during the installation, I'll list them later.

**Comment by vlaze** [comment]
Alright, I've revised again the code and made a few commits. That should be fine for it work properly. Unfortunately, I still have no idea about how to squash commits and softlinking, so there is few more I can do. However, if you have any problem, feel free to comment it here as usual. :+1:

**Comment by vlaze** [comment]
*...* :neutral_face: 

I have tried to rename my commits with `git rebase -i HEAD~24`, and push them here, but it definitely didn't work as expected. I have never used Git before, and I guess it'll be taking some time for me to learn the basics. I apologize for the mess/delay.

**Comment by m000** [comment]
Note that `git rebase -i` only rewrites your _local_ commit history. This means that your local repository will be in conflict with the _remote_ repository (different histories). You will need `git push -f` to force replacing the remote commit history. (It is advised you experiment on a branch before force-pushing.)

Softlinking isn't a big deal. Just use `ln -sf` instead of `cp`.

**Comment by vlaze** [comment]
So should I proceed like...

- Open my project folder and `git rebase -i HEAD~24`

- Edit my commits (can't I delete or hide them to make this look cleaner?)

- `git push -f`

...?


Again, sorry for the inconvenience, it's my first time using Git; thanks for your patience.

**Comment by moyix** [comment]
Yep. That will let you rewrite the history of your fork into something cleaner. The rebase -i lets you squash multiple commits together, so you can end up with just a nice series of patches where each one makes just one well-defined change.

You might want to have a look at the chapter on rewriting history in the Git Book: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by m000** [comment]
Note that if your history is too "polluted" with unrelated changes, it may
be easier to start with a fresh branch from moyix/panda/master.

Then you can cherry-pick specific commits into the fresh branch.
https://git-scm.com/docs/git-cherry-pick

Or, if your commits are "polluted" too, you can manually copy individual
files and commit the changes.

Finally, you send a new pull request from the updated fresh branch.

2016-06-21 14:56 GMT+02:00 Brendan Dolan-Gavitt <notifications@github.com>:

**Comment by vlaze** [comment]
Seems like I could fix this mess a bit. However, I can't change some commit titles, like 'Add files via upload' ones to provide info about what has been done there, nor I can't edit commit commentaries in order to provide extra information. I hope this makes it clearer for you to follow my changes in your program better.

**Comment by vlaze** [comment]
...any update?

**Comment by moyix** [comment]
I think I still don't see why `archer.sh` is necessary. Under what circumstances do you encounter an error that's fixed by running that?

I do see why making the `apt-get update` step independent could prevent errors (e.g. if some of your `sources.list` is unavailable due to network issues), so I think that could be incorporated.

**Comment by vlaze** [comment]
`archer.sh` is not an 'important' update: its main function is to avoid users having to move files recquired in some directories manually. It just moves them by itself regarding the user's architecture. I decided to include it because that same thing happened to me, and I thought it would be nice to automate this process by calling my script in the installation script.

**Comment by moyix** [comment]
Right, the question is – I don't think others have had to move those files manually. So what's different about your environment vs others? Is it repeatable?

**Comment by vlaze** [comment]
I have no idea, I thought it was supposed to be like this, having the user to move the files by its own. I just installed PANDA using `panda_install.bash`, and then I had to move the files by myself (that's when you don't use the script).

**Comment by vlaze** [comment]
After some time, I revised the installation process of PANDA in my computer, and I could confirm that `archer.sh` is not required as an important part of the program. With this final change I hope the pull request can be finally merged. :smile:

**Comment by vlaze** [comment]
News?

**Pull request closed without merging**
