### PR TITLE
PyPANDA: directory overrides for PANDA constructor

### PR DESCRIPTION
**Pull request by MarkMankins**
PANDA and PyPANDA make some assumptions about where files are installed that don't currently align with how things are done in my environment.  I updated both to allow for more fine-grained configuration to be specified.  I can rework if there is a better way.  Is there anything else I need to do - since this logic is tightly coupled between PyPANDA and PANDA I wasn't sure if anything else needed tweaked (version numbers?)

Allow caller to specify location of libpanda shared object, pc-bios files, and directory where plugins are installed.  If these arguments are left as their default values PyPANDA will use the previous algorithm for finding these files.

### CODE REVIEW

**Comment by AndrewFasano** [comment]
These changes look good to me but I'd love for either @lacraig2 or @jamcleod to double check that the `PANDA_LIB` environment variable changes wont' break anything with panda-rs.

**Comment by MarkMankins** [comment]
The output from pypanda's test generic_tests.py doesn't look like it's what is expected - I don't think that originated with this PR.

**Comment by AndrewFasano** [comment]
Oh wow yeah, that looks very wrong. Thanks for catching it. Since the test is still marked as passing despite it going off the rails, I'm going to assume that has been broken for a long time and not related to this PR. I'll open an issue.

**Comment by MarkMankins** [comment]
If there is a chance that PANDA_LIB might cause a problem I could change that to something else.  PYPANDA_PANDA_LIB perhaps?

**Comment by AndrewFasano** [comment]
Nah, I think PANDA_LIB is fine - nobody complained so I'll merge this now. Thanks!

**Pull request merged**
