### PR TITLE
Cleanup for PANDA callbacks + RR control API

### PR DESCRIPTION
**Pull request by m000**
**PANDA callbacks cleanup**
- PANDA callbacks definitions are moved to `callbacks/cb-defs.h` (plugin-side) and `callbacks/cb-support.h`. The latter is auto-generated using the former, minus some exceptions. This makes it easier to keep the two files in-sync. Before, the callback definitions were thrown in `plugin.h`. Also, the old `callback_support.h` header had several naming discrepancies compared to `plugin.h`. This made it harder to sync the occasional changes between the two.
- Most callbacks were declared to return `int` for no good reason. With very few exceptions, the return value of callbacks was not used. For this, return type of callbacks was changed to `void` for most of the callbacks.
- In many cases the argument types of the callbacks were not semantically correct. E.g. using `uint64_t` for addresses or `uint32_t` for sizes, or `void *` for a byte buffer. Types have been fixed for most callback arguments to reflect the actual meaning of the argument. This should help improve the readability of plugin code.
- Comment block preceding callbacks definitions were not uniformly formatted. They have now been reworked so they can be easily parsed. This would allow e.g. to automatically convert them to Doxygen format, so that PANDA documentation can be generated automatically, rather than having to manually update a bunch of markdown files.

**RR control API**
Starting/stopping record/replay required setting some (undocumented) magic globals. These would be checked by the main PANDA loop and carry on the requested action. The magic globals and the `rr_mode` globals have been merged into a new type `rr_control_t` defined in `rr/rr_types.h`. An API for starting/stopping r/r is provided in `rr/rr_api.h`. The changes between modes are now modelled as an FSM, so code using the API can test whether the requested action can be carried out or not.

**Plugin symbol checker script**
Script `build-check.sh` has been added in `panda/scripts`. The script checks all the plugin shared libraries for missing symbols. Symbols must exist either in the plugin itself, or in the PANDA binary. The script can be integrated with `build.sh` and CI, to intercept issues similar to #491.

### CODE REVIEW

**Comment by m000** [comment]
@nathanjackson has already tested this PR. It didn't cause any problems with his test set.

**Comment by nathanjackson** [comment]
@m000 , I've not run the tests against our internal plugins, only the public plugins. I haven't had a chance to go update our internal plugins. Before I go off trying to update them, is it expected that we will have to update them?

**Comment by m000** [comment]
@nathanjackson Some updates will be required but they should be straightforward. From the changes required for the public plugins, the following changes should be enough:
- Fixing the return type of callbacks to `void` and updating `return` statements.
- Fixing the types of callback arguments. You can do this lazily: If the compiler doesn't complain and `build-check.sh` comes clean, you should be fine without changing anything.
- Updating `printf` formats in some cases. `TARGET_PTR_FMT` can be used for guest pointers and `%zu` for `size_t`. Again, if the compiler doesn't complain, leaving the code as-is is fine for an internal plugin. For public plugins it is good to use the proper format so that the plugins can be compiled for all supported host platforms.

**Comment by nathanjackson** [comment]
I've got everything on our end updated and those tests pass now too. The changes to the APIs are good and make much more sense now.

I'm sure @moyix loves it when I poke him to merge stuff 😃 but we need this PR sooner rather than later since it fixes some plugins that we use on a regular basis. Plus we've got some additional PRs already in that we need to revisit in light of #487 and this PR.

**Pull request merged**
