### PR TITLE
migrate max_taintset_compute_number option from taint to taint2

### PR DESCRIPTION
**Pull request by LauraLMann**
In the new taint2 plugin, implemented the max_taintset_compute_number option that existed in the old taint plugin.

### CODE REVIEW

**Comment by LauraLMann** [comment]
Travis checks 3 & 4 timed out.  Close and reopen...

**Comment by LauraLMann** [comment]
...to prompt Travis to try again.

**Comment by LauraLMann** [comment]
This time Travis steps 1 and 2 timed out...

**Comment by LauraLMann** [comment]
...prompt Travis to try again.

**Comment by LauraLMann** [comment]
This time Travis subtests 6, 9 and 10 timed out, and subtest 11 couldn't reach an apt archive (which it reached fine earlier).  Try again...

**Comment by LauraLMann** [comment]
...one more time!

**Comment by LauraLMann** [comment]
Travis checks 7, 8 & 10 timed out.  I don't think that's my fault, so...

**Comment by LauraLMann** [comment]
...try again.

**Comment by LauraLMann** [comment]
Travis 1, 8 and 10 timed out.  Try again.

**Comment by LauraLMann** [comment]
If each Travis subtest is standalone, shouldn't we be able to consider Travis passed if each subtest succeeds in at least one attempt, even though they're not all passing in the same attempt?

**Comment by LauraLMann** [comment]
Only Travis subtest 9 timed out this time.  It has passed in the past on this branch.  You know the drill.  It's like deja vu...

**Comment by LauraLMann** [comment]
...all over again.

**Comment by LauraLMann** [comment]
Travis subtests 8 and 13 timed out...

**Comment by LauraLMann** [comment]
...no idea why.  Try again.  Complain greatly about Travis.

**Comment by LauraLMann** [comment]
Only Travis 5 & 10 timed out this time, but they've succeeded in the past.

**Comment by LauraLMann** [comment]
Grrr.

**Comment by LauraLMann** [comment]
Travis subtests 4, 7 and 14 timed out, even though they've all passed at some time in the past.

**Comment by LauraLMann** [comment]
Force Travis to try again, although I'm thinking Travis needs a major adjustment.  This is ridiculous.

**Comment by moyix** [comment]
Is it possible to tell Travis to only run the first test? The rest are just different compilation flags as far as I can see and I don't think they're likely to give different results for PANDA. I am unfortunately not very familiar with Travis configuration but I'd be happy to accept a PR that did this.

**Comment by LauraLMann** [comment]
Have no idea if I can tell Travis just to run just the first test - I'll ask my local Travis expert.
I have successfully gotten Travis to pass the work on this branch when it was on my fork, by individually restarting each subtest that failed.  Unfortunately, I do not have rights(?) to restart individual tests on this repo.

**Comment by moyix** [comment]
Looks like this past run had only one test failing – so I've restarted just that one.

**Comment by LauraLMann** [comment]
Thanks for restarting the one failed Travis test - looks like you have the magic touch, as they're all good now!

**Comment by moyix** [comment]
Whew. Sorry for all the trouble with Travis. As I said I'd be happy to try and change the config to have it test fewer configurations!

Thanks for the contribution!

**Pull request merged**
